### ISSUE TITLE
support for cycles

### ISSUE THREAD

**Issue by lowellbander** [stevedsun/notion-graph-view#11]
ahoy! thank you so much for creating this repo!

as far as I can tell, the graph view doesn't depict cycles, even if they exist in the underlying notion DB

Would you be able to point me to which pieces of the repo would need to be tweaked to make this possible? I'd be happy to give this a whirl with a little guidance

**Comment by stevedsun** [comment]
Now to avoid infinite loop, the `parser.py` would stop when finding a backlink relationship. I think what you have to implement is a mechanism to check cycle when a block has a backlink.

**Comment by stevedsun** [comment]
In BlockParser class,

```
    def parse_self(self) -> None:
        if self.obj.get('object', None) and self.obj['object'] == 'page':
            obj = notion.pages.retrieve(self.id)
            PageParser(obj)
        if self.obj.get('object', None) and self.obj['object'] == 'database':
            obj = notion.databases.retrieve(self.id)
            DatabaseParser(obj)
        if self.obj.get('object', None) and self.obj['object'] == 'block':
            if self.obj['type'] == 'child_page':
                obj = notion.pages.retrieve(self.id)
                ChildPageParser(obj)
            if self.obj['type'] == 'child_database':
                obj = notion.databases.retrieve(self.id)
                ChildDatabaseParser(obj)
            if self.obj['type'] in ['paragraph', 'bulleted_list_item', 'numbered_list_item', 'to_do', 'toggle', 'callout', 'quote']:
                CommonTextParser(self.obj, self.parent_id)
            if self.obj['type'] == 'link_to_page':
                # Todo(steve): API return unsupport type
                pass
            if self.obj['type'] == 'table':
                TableParser(self.obj, self.parent_id)
            if self.obj['type'] == 'table_row':
                pass
```
The piece of code would check what type of the current block, but Notion's API now is not easy to check "backlinks", therefore if you want to detect cycle, you have to detect "backlinks" at first. (you can refer to this project's code [notion-backlinks-creator](https://github.com/twkrol/notion-backlinks-creator/blob/master/app.py) )

I will refine this code repo to make it easy to read afterwards, so I'm very happy to see you like it.

**Comment by stevedsun** [comment]
Hello, the project has been updated and published to PyPi.
If any chance, please have a try again. Thanks for using.
