### ISSUE TITLE
Crashes while building a graph

### ISSUE THREAD

**Issue by zboucek** [stevedsun/notion-graph-view#15]
Hi there! I'm having trouble using Notion Graph View. When I run the program to generate a graph, it crashes, possibly when encountering a page with a database (in my workspace, it found several nodes before crashing). 

```
File "/home/zboucek/.local/lib/python3.10/site-packages/notion_client/client.py", line 126, in _parse_response
    raise APIResponseError(response, body["message"], code)
notion_client.errors.APIResponseError: Could not find database with ID: **********************. Make sure the relevant pages and databases are shared with your integration.
```
Thanks, the project looks interesting. Just what I was looking for. Hopefully the bug will be resolved soon.

**Comment by stevedsun** [comment]
it seems like that your notion api is not available. please follow the readme section - "Notion api setup".

**Comment by zboucek** [comment]
I mapped the databases successfully, but it crashes when the program reaches the view of the same database on the page. I cannot access the page from error message according to its ID even in browser. I think that problem is getting ID of database from view.

**Comment by stevedsun** [comment]
I tried again and did not encounter the issue you mentioned. The possible reason could be that your database did not grant integration permissions.

**Comment by zboucek** [comment]
I gave access to all the pages just in case. Sometimes the graph for a certain page is created, but sometimes it ends up with an error that the database with the ID cannot be found. I have the pages very interlinked, it seems that this is what is causing the problem. There is no classic tree structure, but sometimes it will bounce to a page that is at a different level than the original one that the graph is built from.

**Comment by stevedsun** [comment]
Hi @zboucek  could you please provide me with an example (a sharing Notion page or a relationship graph) to demonstrate the error in your notes?
