### ISSUE TITLE
中文乱码

### ISSUE THREAD

**Issue by chenshen03** [stevedsun/notion-graph-view#16]
您好，如果笔记有中文，生成的图就会显示乱码
<img width="1222" alt="image" src="https://user-images.githubusercontent.com/20432947/233819009-99aeccbd-2eb8-431a-978e-423984b5027e.png">

**Comment by stevedsun** [comment]
This project is using matplotlib to draw graph. Matplotlib by default does not support displaying Unicode characters such as Chinese, Japanese and Korean characters. This is a temporary solution: [Displaying CJK Characters in Matplotlib Plots](https://albertauyeung.github.io/2020/03/15/matplotlib-cjk-fonts.html/)

**Comment by stevedsun** [comment]
https://github.com/stevedsun/notion-graph-view/pull/17
