### ISSUE TITLE
requests.exceptions.HTTPError: Invalid input - message

### ISSUE THREAD

**Issue by AJJCAIRNS** [stevedsun/notion-graph-view#2]
D:\PycharmProjects\notion-graph-view\venv\Scripts\python.exe D:/PycharmProjects/notion-graph-view/main.py
Root Page: Personal Home
page Personal Home
Traceback (most recent call last):
  File "D:\PycharmProjects\notion-graph-view\main.py", line 30, in <module>
    read_page(config2.my_token_v2, config2.my_url)
  File "D:\PycharmProjects\notion-graph-view\main.py", line 17, in read_page
    bfs_block(base_block)
  File "D:\PycharmProjects\notion-graph-view\main.py", line 24, in bfs_block
    parser = Parser(block)
  File "D:\PycharmProjects\notion-graph-view\parser2.py", line 15, in __init__
    self.parse_page(block)
  File "D:\PycharmProjects\notion-graph-view\parser2.py", line 85, in parse_page
    self.parse_children(page)
  File "D:\PycharmProjects\notion-graph-view\parser2.py", line 74, in parse_children
    self.parse_collection(collection)
  File "D:\PycharmProjects\notion-graph-view\parser2.py", line 45, in parse_collection
    row_blocks = collection.get_rows()
  File "D:\PycharmProjects\notion-graph-view\venv\lib\site-packages\notion\collection.py", line 239, in get_rows
    return self.query(**kwargs)
  File "D:\PycharmProjects\notion-graph-view\venv\lib\site-packages\notion\collection.py", line 236, in query
    return CollectionQuery(self, self._get_a_collection_view(), **kwargs).execute()
  File "D:\PycharmProjects\notion-graph-view\venv\lib\site-packages\notion\collection.py", line 385, in execute
    self._client.query_collection(
  File "D:\PycharmProjects\notion-graph-view\venv\lib\site-packages\notion\client.py", line 294, in query_collection
    return self._store.call_query_collection(*args, **kwargs)
  File "D:\PycharmProjects\notion-graph-view\venv\lib\site-packages\notion\store.py", line 344, in call_query_collection
    response = self._client.post("queryCollection", data).json()
  File "D:\PycharmProjects\notion-graph-view\venv\lib\site-packages\notion\client.py", line 260, in post
    raise HTTPError(
requests.exceptions.HTTPError: Invalid input.

Process finished with exit code 1

**Comment by AJJCAIRNS** [comment]
Can get it to work with a simple page, but doesn't show all links e.g. there is a link from page 3 to page 2 not shown.
![image](https://user-images.githubusercontent.com/92783189/158903124-51856b23-e333-4150-930f-27c34494f306.png)

**Comment by stevedsun** [comment]
Thanks for feedback

**Comment by RayRemnant** [comment]
How did you manage to get it to work?

**Comment by AJJCAIRNS** [comment]
> D:\PycharmProjects\notion-graph-view\venv\Scripts\python.exe D:/PycharmProjects/notion-graph-view/main.py Root Page: Personal Home page Personal Home Traceback (most recent call last): File "D:\PycharmProjects\notion-graph-view\main.py", line 30, in read_page(config2.my_token_v2, config2.my_url) File "D:\PycharmProjects\notion-graph-view\main.py", line 17, in read_page bfs_block(base_block) File "D:\PycharmProjects\notion-graph-view\main.py", line 24, in bfs_block parser = Parser(block) File "D:\PycharmProjects\notion-graph-view\parser2.py", line 15, in **init** self.parse_page(block) File "D:\PycharmProjects\notion-graph-view\parser2.py", line 85, in parse_page self.parse_children(page) File "D:\PycharmProjects\notion-graph-view\parser2.py", line 74, in parse_children self.parse_collection(collection) File "D:\PycharmProjects\notion-graph-view\parser2.py", line 45, in parse_collection row_blocks = collection.get_rows() File "D:\PycharmProjects\notion-graph-view\venv\lib\site-packages\notion\collection.py", line 239, in get_rows return self.query(**kwargs) File "D:\PycharmProjects\notion-graph-view\venv\lib\site-packages\notion\collection.py", line 236, in query return CollectionQuery(self, self._get_a_collection_view(), **kwargs).execute() File "D:\PycharmProjects\notion-graph-view\venv\lib\site-packages\notion\collection.py", line 385, in execute self._client.query_collection( File "D:\PycharmProjects\notion-graph-view\venv\lib\site-packages\notion\client.py", line 294, in query_collection return self._store.call_query_collection(*args, **kwargs) File "D:\PycharmProjects\notion-graph-view\venv\lib\site-packages\notion\store.py", line 344, in call_query_collection response = self._client.post("queryCollection", data).json() File "D:\PycharmProjects\notion-graph-view\venv\lib\site-packages\notion\client.py", line 260, in post raise HTTPError( requests.exceptions.HTTPError: Invalid input.
> 
> Process finished with exit code 1

**Comment by AJJCAIRNS** [comment]
> How did you manage to get it to work?

Just works with a simple page with links to other pages. Not with databases, etc.

**Comment by stevedsun** [comment]
Hi guys, due to Notion upgrades frequently, I'm going to figure out a better solution to do this thing.

**Comment by stevedsun** [comment]
> > How did you manage to get it to work?
> 
> Just works with a simple page with links to other pages. Not with databases, etc.

Now version using Notion API has been updated
