### ISSUE TITLE
link_to_page working properly

### ISSUE THREAD

**Issue by enfycius** [stevedsun/notion-graph-view#24]
Issue #5 
; The API related to link to page appears to be working properly.

My notion consisted of the following:

![스크린샷 2023-11-26 오후 9 49 01](https://github.com/stevedsun/notion-graph-view/assets/34566999/d06053e1-233c-4354-9bf9-d306f723aedf)

The result of the API call is

![스크린샷 2023-11-26 오후 9 49 31](https://github.com/stevedsun/notion-graph-view/assets/34566999/7b1f1aa5-5134-4f64-ba4a-d9cf7221aa11)

**Comment by stevedsun** [comment]
Fixed at release 0.2.7.

**Comment by enfycius** [comment]
@stevedsun Very nice !! Thanks :)
