### ISSUE TITLE
Empty graph

### ISSUE THREAD

**Issue by FormalSnake** [stevedsun/notion-graph-view#25]
This is the command output:
```bash
Parsing ...
Prasing ... done
Graph is generated at: ./Documents/nograph/graph_out.html
```
And I get no web console errors either:
![198](https://github.com/stevedsun/notion-graph-view/assets/90651091/dbc763ed-a141-4729-bf0c-cc9ed9738ccc)

**Comment by FormalSnake** [comment]
Is it because the page is not public or something?

alias nograph="python3 -m notion_graph -p 607bb0093c714cb0999bd0ce7f2afe71 -t secret_... -o ./Documents/nograph/graph_out.html"

**Comment by stevedsun** [comment]
Hi @FormalSnake,
please refer to [Notion Integration](https://developers.notion.com/docs/create-a-notion-integration) Guide and especially make sure your Notion page has connected to the Integration.
![image](https://github.com/stevedsun/notion-graph-view/assets/5465534/cac0f829-98f1-478c-85c7-f0f32976eaf3)

**Comment by FormalSnake** [comment]
Ok!
