### ISSUE TITLE
Getting runtime error even after providing credentials

### ISSUE THREAD

**Issue by siocean** [stevedsun/notion-graph-view#7]
I am really trying to make this work. However, I am getting error when launching main.py. When I run config.py I get runtime error saying that I have not entered by credentials but in fact I have. Can anyone help? Thank you.

**Comment by stevedsun** [comment]
maybe you have not set your Notion page sharing to your integration account.

**Comment by siocean** [comment]
I have done that. Created a token and shared it with a page.
