### ISSUE TITLE
Could not find block with ID ****

### ISSUE THREAD

**Issue by bartrietveld** [stevedsun/notion-graph-view#8]
Once running main.py

/notion-graph-view/env/lib/python3.10/site-packages/notion_client/client.py", line 126, in _parse_response
    raise APIResponseError(response, body["message"], code)
notion_client.errors.APIResponseError: Could not find block with ID: **************************. Make sure the relevant pages and databases are shared with your integration.

I could not find the option to share the specific page with an integration. How can this be done?

**Comment by stevedsun** [comment]
Please refer to the README file, you have to create an integration at <https://www.notion.so/my-integrations>. Then share your target Notion page to the integration account.

**Comment by bartrietveld** [comment]
Thank you for replying so quickly.

I have created an integration, but I could not find anywhere how to share
the page. I have found this now, since it was not under sharing, but I had
to create a new connection from a Notion page.
